# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.license_data import LicenseData  # noqa: F401,E501
from swagger_server import util


class License(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, license: LicenseData=None):  # noqa: E501
        """License - a model defined in Swagger

        :param id: The id of this License.  # noqa: E501
        :type id: int
        :param license: The license of this License.  # noqa: E501
        :type license: LicenseData
        """
        self.swagger_types = {
            'id': int,
            'license': LicenseData
        }

        self.attribute_map = {
            'id': '_id',
            'license': 'license'
        }
        self._id = id
        self._license = license

    @classmethod
    def from_dict(cls, dikt) -> 'License':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The license of this License.  # noqa: E501
        :rtype: License
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this License.

        Unique license identifier  # noqa: E501

        :return: The id of this License.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this License.

        Unique license identifier  # noqa: E501

        :param id: The id of this License.
        :type id: int
        """

        self._id = id

    @property
    def license(self) -> LicenseData:
        """Gets the license of this License.


        :return: The license of this License.
        :rtype: LicenseData
        """
        return self._license

    @license.setter
    def license(self, license: LicenseData):
        """Sets the license of this License.


        :param license: The license of this License.
        :type license: LicenseData
        """

        self._license = license
